### ISSUE TITLE
Merge branch 1-0-stable and open a new branch. 

### ISSUE THREAD

**Issue by ytbryan** [ytbryan/devops-resources#46]
Somebody got to take the scissor and do a cut. The branch has over 31 commits ahead. Merge existing PR. Pause the pull requests. Do a merge. I prefer someone who has no experience to do it. maybe @hadibolehjadi or @shankjs  or @ReubenChan 

Once you are done with merging, please branch out a 1-1-stable and continue from there.

cc @dennislwm @huskypower @ylcheryl @ReubenChan

**Comment by shankjs** [comment]
I'll give it a shot. Thanks guys.

**Comment by ReubenChan** [comment]
Count me in too, Maybe we can share the load?

**Comment by ytbryan** [comment]
ok closed because of #48
