### ISSUE TITLE
Decide to use this repo or to use the new repo 

### ISSUE THREAD

**Issue by ytbryan** [ytbryan/devops-resources#47]
We can either use this repo by renaming it to `devops-resources` (easy)

or we can plan to commit things in the new repo. 

The latter will start from the beginning with no history. The former has some git history that may not be perfect. I'm cool with both approaches.

**Comment by shankjs** [comment]
My take is to rename it. Reason being, the history is good to learn from our mistakes as we can view it. Downside is of course we won't experience transfer of repo from one to another. Though that can be done on a smaller scale for practice

Will go with what the majority think is good way forward. 

cc @dennislwm @ReubenChan @huskypower @ylcheryl @hadibolehjadi

**Comment by ReubenChan** [comment]
Good Morning,
I am transparent with both approaches too... able learn both ways to determine which is better in the long run...
